### ISSUE TITLE
Button to decrypt the encrypted messages.

### ISSUE THREAD

**Issue by encrypted-soul** [muke1908/chat-e2ee#63]
Once the browser is reloaded the sent messages get transformed to their hashed form. Prevent this from happening.

Before reload
![issue3](https://user-images.githubusercontent.com/62807661/89912816-9e33be00-dc10-11ea-9943-202c59c7044e.png)

After reload
![issue4](https://user-images.githubusercontent.com/62807661/89912847-a7248f80-dc10-11ea-9752-183d1cbe4203.png)

**Comment by muke1908** [comment]
@gagan-aryan it's kind of intentional for following reasons: 
1. Decryption is quite a computation heavy.
2. Messages in the app are meant to be short-lived.
3. In any case if the key pairs are changed, we can't decrypt the message anyway. 

Suggestion for better UX:
A button can be attached to each message block, if clicked on it, it'll try to decrypt the message with current key pair - if succeed show the message otherwise leave it as it is.

**Comment by gagan-aryan** [comment]
3. Could you elaborate on the third point? Because my understanding is that public and private key are generated only once. Isn't that the case? Does the private key keeps changing?

For UI - Can we also add an alert message when someone tries to reload the page that would say that the messages would henceforth, be seen in their encrypted form?

**Comment by muke1908** [comment]
> @muke1908
> 3. Could you elaborate on the third point? Because my understanding is that public and private key are generated only once. Isn't that the case? Does the private key keeps changing?

Yes, it's generated only once at the beginning of every chat session.  **If changed** or **lost**, previously encrypted messages with the old key cant be decrypted.  - which is expected behavior. 
---
On refresh, the client will still have the keys and technically would be able to decrypt.  But on refresh, decrypting all messages at one shot will be heavy on client-side.

**Comment by gagan-aryan** [comment]
Okay, I got it. 
So what is the final UI we will be implementing then?

**Comment by gagan-aryan** [comment]
We can even simply clear all the previous messages once we reload

**Comment by muke1908** [comment]
> We can even simply clear all the previous messages once we reload

That can be misleading. Let's add a button to decrypt which will try to decrypt the message with the existing key. I'll update the issue with more detail info.

**Comment by muke1908** [comment]
Let's have a button for the messages that are in an encrypted format.
Based on the encrypted flag at 
https://github.com/muke1908/chat-e2ee/blob/b67523213a58b2e9bd156fbd0c232706c090f50e/client/src/pages/messaging/index.js#L215
needs to show the button. 

![decrypt](https://user-images.githubusercontent.com/20297989/90053498-41ed9e80-dce3-11ea-99b3-7b391f2ef037.png)
